# -*- coding: utf-8 -*-
"""Genera el INSERT de catálogo.colegios a partir de los centros observados."""
# (slug, nombre, nombre_corto, municipio, provincia, orden)
NUEVOS = [
 # --- centros de familias y profesores, Comunidad de Madrid ---
 ('menesiano','Colegio Menesiano','Menesiano','Madrid','Madrid',20),
 ('joyfe','Colegio Joyfe','Joyfe','Madrid','Madrid',21),
 ('ramiro-de-maeztu','IES Ramiro de Maeztu','Ramiro de Maeztu','Madrid','Madrid',22),
 ('gredos-san-diego','Gredos San Diego','GSD',None,'Madrid',23),
 ('gredos-san-diego-las-suertes','Gredos San Diego Las Suertes','GSD Las Suertes','Getafe','Madrid',24),
 ('gredos-san-diego-guadarrama','Gredos San Diego Guadarrama','GSD Guadarrama','Guadarrama','Madrid',25),
 ('santo-angel-british-school','Santo Ángel British School','Santo Ángel',None,'Madrid',26),
 ('retamar','Colegio Retamar','Retamar','Pozuelo de Alarcón','Madrid',27),
 ('mater-inmaculata','Colegio Mater Inmaculata','Mater Inmaculata','Alcobendas','Madrid',28),
 ('senara','Colegio Senara','Senara','Madrid','Madrid',29),
 ('casa-de-la-virgen','Colegio Casa de la Virgen','Casa de la Virgen','Madrid','Madrid',30),
 ('arturo-soria','Colegio Arturo Soria','Arturo Soria','Madrid','Madrid',31),
 ('el-valle-valdebernardo','Colegio El Valle Valdebernardo','El Valle Valdebernardo','Madrid','Madrid',32),
 ('el-valle-las-tablas','Colegio El Valle Las Tablas','El Valle Las Tablas','Madrid','Madrid',33),
 ('jesus-maria','Colegio Jesús María','Jesús María','Madrid','Madrid',34),
 ('santa-ana-y-san-rafael','Colegio Santa Ana y San Rafael','Santa Ana y San Rafael','Madrid','Madrid',35),
 ('aldovea','Colegio Aldovea','Aldovea','Alcobendas','Madrid',36),
 ('el-prado','Colegio El Prado','El Prado','Madrid','Madrid',37),
 ('internacional-aravaca','Colegio Internacional Aravaca','Internacional Aravaca','Madrid','Madrid',38),
 ('maria-teresa-alcobendas','Colegio María Teresa','María Teresa','Alcobendas','Madrid',39),
 ('las-irlandesas-el-soto','Colegio Las Irlandesas El Soto','Las Irlandesas','Boadilla del Monte','Madrid',40),
 ('la-salle-maravillas','Colegio La Salle Maravillas','La Salle Maravillas','Madrid','Madrid',41),
 ('la-salle-san-jose','Colegio La Salle San José','La Salle San José','Madrid','Madrid',42),
 ('liceo-sorolla','Liceo Sorolla','Liceo Sorolla','Pozuelo de Alarcón','Madrid',43),
 ('los-sauces-la-moraleja','Colegio Los Sauces La Moraleja','Los Sauces','Alcobendas','Madrid',44),
 ('los-robles','Colegio Los Robles','Los Robles',None,'Madrid',45),
 ('colegio-zola-las-rozas','Colegio Zola Las Rozas','Zola Las Rozas','Las Rozas de Madrid','Madrid',46),
 ('san-gabriel-alcala','Colegio San Gabriel','San Gabriel','Alcalá de Henares','Madrid',47),
 ('sagrado-corazon-capuchinos','Colegio Sagrado Corazón (Capuchinos)','Sagrado Corazón','Madrid','Madrid',48),
 ('sagrada-familia','Colegio Sagrada Familia','Sagrada Familia',None,'Madrid',49),
 ('nuestra-senora-de-la-merced','Colegio Nuestra Señora de la Merced','La Merced','Madrid','Madrid',50),
 ('nuestra-senora-del-buen-consejo','Colegio Nuestra Señora del Buen Consejo','Buen Consejo','Madrid','Madrid',51),
 ('stella-maris-fesd','Colegio Stella Maris (FESD)','Stella Maris','Madrid','Madrid',52),
 ('litterator-aranjuez','Colegio Litterator','Litterator','Aranjuez','Madrid',53),
 ('ceip-nuestra-senora-de-la-natividad','CEIP Nuestra Señora de la Natividad','Ntra. Sra. de la Natividad','Cedillo del Condado','Toledo',54),
 ('virgen-de-la-caridad-illescas','Colegio Virgen de la Caridad','Virgen de la Caridad','Illescas','Toledo',55),
 # --- institutos públicos de Madrid ---
 ('ies-fortuny','IES Fortuny','Fortuny','Madrid','Madrid',60),
 ('ies-carlos-camo','IES Carlos Camo','Carlos Camo',None,'Madrid',61),
 ('ies-cervantes','IES Cervantes','Cervantes','Madrid','Madrid',62),
 ('ies-juan-de-la-cierva','IES Juan de la Cierva','Juan de la Cierva','Madrid','Madrid',63),
 ('ies-san-juan-bautista','IES San Juan Bautista','San Juan Bautista','Madrid','Madrid',64),
 ('ies-villablanca','IES Villablanca','Villablanca','Madrid','Madrid',65),
 ('ies-antonio-machado','IES Antonio Machado','Antonio Machado',None,'Madrid',66),
 ('ies-gerardo-diego','IES Gerardo Diego','Gerardo Diego',None,'Madrid',67),
 ('ies-profesor-julio-perez','IES Profesor Julio Pérez','Julio Pérez','Rivas-Vaciamadrid','Madrid',68),
 ('ies-cardenal-cisneros','IES Cardenal Cisneros','Cardenal Cisneros','Madrid','Madrid',69),
 ('ies-carmen-martin-gaite','IES Carmen Martín Gaite','Carmen Martín Gaite','Moralzarzal','Madrid',70),
 ('ies-diego-velazquez','IES Diego Velázquez','Diego Velázquez','Torrelodones','Madrid',71),
 ('ies-rey-pastor','IES Rey Pastor','Rey Pastor','Madrid','Madrid',72),
 ('ceip-el-sol','CEIP El Sol','El Sol','Madrid','Madrid',73),
 ('ccp-palomeras','Colegio Palomeras','Palomeras','Madrid','Madrid',74),
 ('cesur-madrid-ii','Cesur Madrid II','Cesur','Madrid','Madrid',75),
 ('trinity-college','Trinity College','Trinity',None,'Madrid',76),
 # --- centros de fuera de Madrid ---
 ('claret-askartza','Colegio Claret Askartza','Claret Askartza','Leioa','Bizkaia',80),
 ('blanca-de-castilla-burgos','Colegio Blanca de Castilla (Jesuitinas)','Blanca de Castilla','Burgos','Burgos',81),
 ('sagrado-corazon-pamplona','Colegio Sagrado Corazón','Sagrado Corazón','Pamplona','Navarra',82),
 ('maristas-jaen','Colegio Maristas','Maristas','Jaén','Jaén',83),
 ('ies-ciudad-de-jaen','IES Ciudad de Jaén','Ciudad de Jaén','Madrid','Madrid',84),
 ('colegio-obradoiro','Colegio Obradoiro','Obradoiro','A Coruña','A Coruña',85),
 ('ies-rosalia-de-castro','IES Rosalía de Castro','Rosalía de Castro','Santiago de Compostela','A Coruña',86),
 ('compania-de-maria','Colegio Compañía de María','Compañía de María',None,None,87),
 ('ies-german-sanchez-ruiperez','IES Germán Sánchez Ruipérez','Germán Sánchez Ruipérez','Guijuelo','Salamanca',88),
 ('ies-doctor-alarcon-santon','IES Doctor Alarcón Santón','Doctor Alarcón Santón',None,None,89),
 ('ies-salduba','IES Salduba','Salduba','San Pedro de Alcántara','Málaga',90),
 ('ies-playamar','IES Playamar','Playamar','Torremolinos','Málaga',91),
 ('ceip-sancti-petri','CEIP Sancti Petri','Sancti Petri','Chiclana de la Frontera','Cádiz',92),
 ('jesus-maria-valencia','Colegio Jesús María Fernando el Católico','Jesús María Valencia','Valencia','Valencia',93),
 ('san-luis-gonzaga','Colegio San Luis Gonzaga','San Luis Gonzaga',None,None,94),
 ('real-instituto-jovellanos','Real Instituto de Jovellanos','Jovellanos','Gijón','Asturias',95),
 ('trilce-surco','Colegio Trilce Surco','Trilce','Lima','Perú',96),
 ('colegio-zazuar','Colegio Zazuar','Zazuar','Madrid','Madrid',97),
 ('colegio-montserrat','Colegio Montserrat','Montserrat','Madrid','Madrid',98),
 ('ievc-blanch-londres','IEVC Blanch','Blanch',None,None,99),
]

def sql(v):
    return 'NULL' if v is None else "'" + v.replace("'", "''") + "'"

for s, n, c, m, p, o in NUEVOS:
    print(f"  ({sql(s)+',':40s}{sql(n)+',':50s}{sql(c)+',':34s}{sql(m)+',':28s}{sql(p)+',':16s}FALSE, {o}),")
